### ISSUE TITLE
PF2E Diagonals not correct

### ISSUE THREAD

**Issue by jtgrice** [caewok/fvtt-elevation-ruler#195]
Hiya! Elevation ruler is goofing up my diagonals in PF2E, making them go 5-10-15-20 instead of 5-15-20-30 like they should. I'm certain it's Elevation Ruler doing this, since I turned off every other module and the problem was still there (with token dragging AND the measure tool), then I turned off Elevation Ruler and the problem was fixed. I tried checking Prefer Euclidean Distance in the options but that didn't do anything. Would appreciate help! Thank you!

**Comment by caewok** [comment]
Try it in v0.10.7, just released.

**Comment by PhyX-Meow** [comment]
The bug was fixed, but now if you choose 1-2-1 movement in settings, tokens will move like 10-5-10. And 2-1-2 in settings gives 5-10-5. They may need to be swapped :)

**Comment by caewok** [comment]
Yep, flipped a 0 and a 1.

**Comment by jtgrice** [comment]
Fixed! Thank you =)

**Comment by NdranC** [comment]
Is this fix already released? I have the latest version and I'm still getting 10-5-10.

**Comment by PhyX-Meow** [comment]
@NdranC No, but you can choose 10-5-10 in settings to get 5-10-5 as a workaround.

**Comment by NdranC** [comment]
Thank you. I forgot this was part of core foundry now. I was looking for them in the elevation ruler settings.

**Comment by caewok** [comment]
Fixed in v0.10.8.

**Comment by PhyX-Meow** [comment]
@caewok Sorry, but the flip is not yet fixed. I get still reversed result. And I even get same result after I manually edited https://github.com/caewok/lib-geometry/blob/0da25ed79a39f25a398e1e39cff925312ab97536/grid_distance.js#L161 back to it was.

**Comment by sunyatacyte** [comment]
I still have this issue also :)

**Comment by caewok** [comment]
Try it in v0.10.9!
